kind: pipeline
name: RAD KERNEL BUILD GCC

clone:
  disable: true

steps:
- name: gnu-gcc oldcam
  image: archlinux:latest
  environment:
      TELEGRAM_TOKEN:
        from_secret: TG_BOT_API
  commands:
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel bc curl zip wget git --noconfirm
    - # echo “deb http://ftp.us.debian.org/debian testing main contrib non-free” >> /etc/apt/sources.list
    - # apt-get update
    - # apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential bison flex zip gcc clang libc6 curl libstdc++6 git wget libssl-dev && apt-get -y install gcc-arm-linux-gnueabi && apt-get -y install p7zip-full python python2 python3 python3-pip
    - git clone --depth=1 --quiet https://github.com/zebusen/android_kernel_xiaomi_whyred.git -b test2 source && cd source
    - # git clone --depth=1 --quiet https://github.com/attack11/Whyred.git -b extended
    - # git clone --depth=1 --quiet https://github.com/Pzqqt/android_kernel_xiaomi_whyred.git -b panda-qrebase
    - # git clone --depth=1 --quiet https://github.com/STRIX-Project/STRIX_kernel_xiaomi-sdm660.git -b sdm660-eas-test
    - # git clone --depth=1 --quiet https://github.com/Pzqqt/android_kernel_xiaomi_whyred-4.19.git -b panda
    - # git clone --depth=1 --quiet https://github.com/OdSazib/halcyon_kernel_xiaomi_sdm660.git -b eas
    - # git clone --depth=1 --quiet https://github.com/pix106/android_kernel_xiaomi_sdm660_southwest.git -b 11.0-eas-wifi-p
    - git clone --depth=1 --quiet https://github.com/zebusen/buildscript.git
    - script -c "bash -x buildscript/rad.sh --gcc10 --oldcam --lto"
    - # script -c "bash -x myscript/strixeas.sh"
    - # script -c "bash -x myscript/panda419.sh"
    - # script -c "bash -x myscript/extended.sh"
    - # script -c "bash -x myscript/panda.sh"
    - # script -c "bash -x myscript/halycon.sh"
    - # script -c "bash -x myscript/south.sh"
    - #com
