kind: pipeline
name: RAD KERNEL BUILD GCC

clone:
  disable: true

steps:
- name: gnu-gcc oldcam
  image: archlinux:latest
  environment:
      TELEGRAM_TOKEN:
        from_secret: TG_BOT_API
  commands:
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel bc curl zip wget git --noconfirm
    - # echo “deb http://ftp.us.debian.org/debian testing main contrib non-free” >> /etc/apt/sources.list
    - # apt-get update
    - # apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential bison flex zip gcc clang libc6 curl libstdc++6 git wget libssl-dev && apt-get -y install gcc-arm-linux-gnueabi && apt-get -y install p7zip-full python python2 python3 python3-pip
    - git clone --depth=1 --quiet https://github.com/zebusen/android_kernel_xiaomi_whyred.git -b staging-eas source && cd source
    - git clone --depth=1 --quiet https://github.com/zebusen/buildscript.git
    - script -c "bash -x buildscript/rad.sh --aosp-clang --oldcam"
