kind: pipeline
name: RAD KERNEL BUILD GCC

clone:
  disable: true

steps:
- name: gnu-gcc oldcam
  image: archlinux:latest
  environment:
      TELEGRAM_TOKEN:
        from_secret: TG_BOT_API
  commands:
    - curl https://raw.githubusercontent.com/theradcolor/lazyscripts/master/etc/workaround > workaround && bash workaround
    - pacman -Sy base-devel bc curl zip wget git --noconfirm
    - git clone --depth=1 --quiet https://github.com/zebusen/android_kernel_xiaomi_whyred.git -b slmk-test2 source && cd source
    - git clone --depth=1 --quiet https://github.com/zebusen/buildscript.git
    - script -c "bash -x buildscript/rad.sh --gcc-gnu --oldcam --gnu-10"
